---
blank_issues_enabled: false
contact_links:
  - name: General Question ğŸ’¬â“
    url: https://github.com/blat-ai/rawjs2dict/discussions/categories/q-a
    about: Ask and answer questions by creating discussions.